# Cloud Build pipeline that refreshes datasets, backfills raw spot klines,
# triggers multi-horizon signal generation, and publishes a trade-ready report
# to Cloud Storage. Intended to be triggered hourly via Cloud Scheduler.

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s

substitutions:
  _PROJECT_ID: "jc-financial-466902"
  _SPOT_GCS_BUCKET: "jc-financial-466902-btc-forecast-data"
  _REPORT_BUCKET: "gs://jc-financial-466902-btc-forecast-data"

availableSecrets:
  secretManager:
    - versionName: projects/jc-financial-466902/secrets/trade-service-url/versions/latest
      env: SERVICE_URL

steps:
  - id: run-dataset-refresh
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    secretEnv:
      - SERVICE_URL
    args:
      - -c
      - |
        set -euo pipefail
        echo "Calling /run-dataset-refresh (72h window)"
        curl --fail --show-error --silent \
          --request POST "${SERVICE_URL}/run-dataset-refresh" \
          --header "Content-Type: application/json" \
          --data '{"dry_run": false, "args": ["--hours", "72"]}' \
          | tee /workspace/run_dataset_refresh.json

  - id: sync-spot-raw-table
    name: python:3.11
    entrypoint: bash
    env:
      - PROJECT_ID=${_PROJECT_ID}
      - SPOT_GCS_BUCKET=${_SPOT_GCS_BUCKET}
      - PYTHONPATH=/workspace
    args:
      - -c
      - |
        set -euo pipefail
        pip install --no-cache-dir google-cloud-bigquery >/dev/null
        python -m src.scripts.ensure_spot_raw_sync

  - id: run-signal
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    secretEnv:
      - SERVICE_URL
    args:
      - -c
      - |
        set -euo pipefail
        echo "Calling /run-signal with horizons 1,4,8,12"
        curl --fail --show-error --silent \
          --request POST "${SERVICE_URL}/run-signal" \
          --header "Content-Type: application/json" \
          --data '{"dry_run": false, "args": ["--targets", "1,4,8,12"]}' \
          | tee /workspace/run_signal.json

    - id: build-report
    name: python:3.11
    entrypoint: bash
    env:
      - REPORT_BUCKET=${_REPORT_BUCKET}
      - PYTHONPATH=/workspace
    args:
      - -c
      - |
        set -euo pipefail
      python -m src.scripts.build_trade_ready_report

  - id: publish-report
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        REPORT_URI=$(cat /workspace/report_uri.txt)
        gsutil cp /workspace/trade_ready_report.json "${REPORT_URI}"
