from __future__ import annotations

from pathlib import Path
from typing import Any, List, Mapping


def build_walkforward_validation_command(
    *,
    python: str,
    dataset_path: Path,
    walkforward_target: str,
    folds: int,
    train_size: int,
    val_size: int,
    test_size: int,
    gap: int,
    purge_size: int,
    embargo_size: int,
    mode: str,
    model_kind: str,
    signal_threshold: float,
    fee_bps: float,
    slippage_bps: float,
    output_path: Path,
) -> List[str]:
    return [
        python,
        "-m",
        "src.scripts.run_walkforward_validation",
        "--dataset-path",
        str(dataset_path),
        "--y-key",
        str(walkforward_target),
        "--folds",
        str(int(folds)),
        "--train-size",
        str(int(train_size)),
        "--val-size",
        str(int(val_size)),
        "--test-size",
        str(int(test_size)),
        "--gap",
        str(int(gap)),
        "--purge-size",
        str(int(purge_size)),
        "--embargo-size",
        str(int(embargo_size)),
        "--mode",
        str(mode),
        "--model-kind",
        str(model_kind),
        "--signal-threshold",
        str(float(signal_threshold)),
        "--fee-bps",
        str(float(fee_bps)),
        "--slippage-bps",
        str(float(slippage_bps)),
        "--output",
        str(output_path),
    ]


def build_label_ablation_command(
    *,
    python: str,
    summary_dir: Path,
    label_ablation_cfg: Mapping[str, Any],
    quality_cfg: Mapping[str, Any],
    selected_model_kind: str,
    cv_folds: int,
    cv_train_size: int,
    cv_val_size: int,
    cv_test_size: int,
    cv_gap: int,
    cv_purge_size: int,
    cv_embargo_size: int,
    cv_mode: str,
    feature_reliability_json: str | Path | None = None,
    feature_reliability_min_score: float | None = None,
) -> List[str]:
    cmd = [
        python,
        "-m",
        "src.scripts.run_label_ablation",
        "--output-dir",
        str(summary_dir / "label_ablation"),
        "--threshold",
        str(float(label_ablation_cfg.get("threshold", 0.0))),
        "--walkforward-folds",
        str(int(label_ablation_cfg.get("folds", cv_folds))),
        "--walkforward-train-size",
        str(int(label_ablation_cfg.get("train_size", cv_train_size))),
        "--walkforward-val-size",
        str(int(label_ablation_cfg.get("val_size", cv_val_size))),
        "--walkforward-test-size",
        str(int(label_ablation_cfg.get("test_size", cv_test_size))),
        "--walkforward-gap",
        str(int(label_ablation_cfg.get("gap", cv_gap))),
        "--walkforward-purge",
        str(int(label_ablation_cfg.get("purge_size", cv_purge_size))),
        "--walkforward-embargo",
        str(int(label_ablation_cfg.get("embargo_size", cv_embargo_size))),
        "--walkforward-mode",
        str(label_ablation_cfg.get("mode", cv_mode)),
        "--model-kind",
        str(label_ablation_cfg.get("model_kind", selected_model_kind)),
        "--signal-threshold",
        str(float(label_ablation_cfg.get("signal_threshold", quality_cfg.get("walkforward_signal_threshold", 0.5)))),
        "--fee-bps",
        str(float(label_ablation_cfg.get("fee_bps", quality_cfg.get("walkforward_fee_bps", 2.0)))),
        "--slippage-bps",
        str(float(label_ablation_cfg.get("slippage_bps", quality_cfg.get("walkforward_slippage_bps", 1.0)))),
        "--economics-min-trades",
        str(float(label_ablation_cfg.get("economics_min_trades", quality_cfg.get("min_trade_count", 10)))),
        "--economics-min-cum-ret",
        str(float(label_ablation_cfg.get("economics_min_cum_ret", quality_cfg.get("min_net_return", 0.0)))),
        "--economics-turnover-penalty",
        str(float(label_ablation_cfg.get("economics_turnover_penalty", 0.002))),
        "--economics-downside-penalty",
        str(float(label_ablation_cfg.get("economics_downside_penalty", 2.0))),
    ]
    if feature_reliability_json:
        cmd.extend(["--feature-reliability-json", str(feature_reliability_json)])
        cmd.extend(["--feature-reliability-min-score", str(float(feature_reliability_min_score or 0.55))])
    return cmd


def build_point_in_time_audit_command(
    *,
    python: str,
    walkforward_dataset: Path,
    walkforward_target: str,
    leakage_cfg: Mapping[str, Any],
    output_path: Path,
) -> List[str]:
    return [
        python,
        "-m",
        "src.scripts.audit_point_in_time_integrity",
        "--dataset-path",
        str(walkforward_dataset),
        "--y-key",
        str(leakage_cfg.get("y_key", walkforward_target)),
        "--leakage-corr-alert",
        str(float(leakage_cfg.get("corr_alert", 0.98))),
        "--output",
        str(output_path),
    ]


def build_cv_stress_sweep_command(
    *,
    python: str,
    walkforward_dataset: Path,
    walkforward_target: str,
    cv_stress_cfg: Mapping[str, Any],
    folds: int,
    train_size: int,
    val_size: int,
    test_size: int,
    cv_gap: int,
    cv_mode: str,
    output_path: Path,
) -> List[str]:
    return [
        python,
        "-m",
        "src.scripts.run_cv_stress_sweep",
        "--dataset-path",
        str(walkforward_dataset),
        "--y-key",
        str(cv_stress_cfg.get("y_key", walkforward_target)),
        "--folds",
        str(int(folds)),
        "--train-size",
        str(int(train_size)),
        "--val-size",
        str(int(val_size)),
        "--test-size",
        str(int(test_size)),
        "--gap",
        str(int(cv_stress_cfg.get("gap", cv_gap))),
        "--purge-list",
        str(cv_stress_cfg.get("purge_list", "0,12,24")),
        "--embargo-list",
        str(cv_stress_cfg.get("embargo_list", "0,12,24")),
        "--mode",
        str(cv_stress_cfg.get("mode", cv_mode)),
        "--output",
        str(output_path),
    ]