from __future__ import annotations

from pathlib import Path
from typing import Any, List, Mapping


def build_walkforward_model_compare_command(
    *,
    python: str,
    dataset_path: Path,
    walkforward_target: str,
    compare_cfg: Mapping[str, Any],
    quality_cfg: Mapping[str, Any],
    cv_folds: int,
    cv_train_size: int,
    cv_val_size: int,
    cv_test_size: int,
    cv_gap: int,
    cv_purge_size: int,
    cv_embargo_size: int,
    cv_mode: str,
    default_min_train_size: int,
    default_min_val_size: int,
    default_min_test_size: int,
    default_selection_policy: str,
    output_path: Path,
) -> List[str]:
    cmd = [
        python,
        "-m",
        "src.scripts.compare_walkforward_models",
        "--dataset-path",
        str(dataset_path),
        "--y-key",
        str(walkforward_target),
        "--folds",
        str(int(compare_cfg.get("folds", cv_folds))),
        "--train-size",
        str(int(compare_cfg.get("train_size", cv_train_size))),
        "--val-size",
        str(int(compare_cfg.get("val_size", cv_val_size))),
        "--test-size",
        str(int(compare_cfg.get("test_size", cv_test_size))),
        "--gap",
        str(int(compare_cfg.get("gap", cv_gap))),
        "--purge-size",
        str(int(compare_cfg.get("purge_size", cv_purge_size))),
        "--embargo-size",
        str(int(compare_cfg.get("embargo_size", cv_embargo_size))),
        "--mode",
        str(compare_cfg.get("mode", cv_mode)),
        "--min-train-size",
        str(int(compare_cfg.get("min_train_size", default_min_train_size))),
        "--min-val-size",
        str(int(compare_cfg.get("min_val_size", default_min_val_size))),
        "--min-test-size",
        str(int(compare_cfg.get("min_test_size", default_min_test_size))),
        "--signal-threshold",
        str(float(compare_cfg.get("signal_threshold", quality_cfg.get("walkforward_signal_threshold", 0.5)))),
        "--fee-bps",
        str(float(compare_cfg.get("fee_bps", quality_cfg.get("walkforward_fee_bps", 2.0)))),
        "--slippage-bps",
        str(float(compare_cfg.get("slippage_bps", quality_cfg.get("walkforward_slippage_bps", 1.0)))),
        "--rolling-guard" if bool(compare_cfg.get("rolling_guard", True)) else "",
        "--meta-margin",
        str(float(compare_cfg.get("meta_margin", 0.0))),
        "--meta-min-rolling-trades",
        str(int(compare_cfg.get("meta_min_rolling_trades", 0))),
        "--selection-policy",
        str(compare_cfg.get("selection_policy", default_selection_policy)),
        "--min-auc",
        str(float(compare_cfg.get("min_auc", 0.5))),
        "--output",
        str(output_path),
    ]
    return [part for part in cmd if part != ""]